popular_cities = [
    "Paris, France",
    "Rome, Italy",
    "Barcelona, Spain",
    "New York City, USA",
    "Tokyo, Japan",
    "Bangkok, Thailand",
    "Istanbul, Turkey",
    "Sydney, Australia",
    "Cairo, Egypt",
    "Rio de Janeiro, Brazil",
    "Amsterdam, Netherlands",
    "Los Angeles, USA",
    "Berlin, Germany",
    "Venice, Italy",
    "San Francisco, USA",
    "Florence, Italy",
    "Prague, Czech Republic",
    "Dubai, United Arab Emirates",
    "Singapore, Singapore",
    "Seoul, South Korea",
    "Hong Kong, China",
    "Lisbon, Portugal",
    "Vancouver, Canada",
    "Kyoto, Japan",
    "Madrid, Spain",
    "Buenos Aires, Argentina",
    "Mexico City, Mexico",
    "Vienna, Austria",
    "Beijing, China",
    "Marrakech, Morocco",
    "Edinburgh, Scotland",
    "Toronto, Canada",
    "Dublin, Ireland",
    "Athens, Greece",
    "Budapest, Hungary",
    "Sydney, Australia",
    "Prague, Czech Republic",
    "Copenhagen, Denmark",
    "Krakow, Poland",
    "Cape Town, South Africa",
    "Seville, Spain",
    "Florence, Italy",
    "Vancouver, Canada",
    "Montreal, Canada",
    "Amsterdam, Netherlands",
    "Rome, Italy",
    "Zurich, Switzerland",
    "Buenos Aires, Argentina",
    "Berlin, Germany",
    "Hong Kong, China",
]

test_city = ['Nashville, TN']
